#!/bin/bash

echo Cake Runner

bootstrapFileName="build.sh"
cakeFileName="build.cake"

if [ -z "$1" ]; then
  echo "No command passed"
  exit 1
fi

# Find build.cake paths
declare cakeBasePath

while [ ! "$PWD" == "/" ] ; do
  # echo Looking in folder $PWD
  path=(`find . -maxdepth 1 -name "$cakeFileName"`)

  if [ "${#path[@]}" -eq "1" ]; then
    break
  fi
  
  if [ "${#path[@]}" -gt "1" ]; then
    echo "It was found multiple $cakeFileName files"

    for i in "${path[@]}"; do
      echo "$i"
    done
    exit 1
  fi

  cd ..
done

if [ "$PWD" == "/" ]; then
  echo "It was not possible to find the $cakeFileName file."
  exit 1
fi

# Check for the bootstrap script file
if [ ! -e "./$bootstrapFileName" ]; then
  echo "The file $PWD/$bootstrapFileName does not exist or is executable"
  exit 1;
fi

./$bootstrapFileName --target=$1
