#!/bin/bash

echo Cake Runner

source "$( dirname "${BASH_SOURCE[0]}")/../get-cake-basepath.sh"

bootstrapFileName="build.sh"
cakeFileName="build.cake"

if [ -z "$1" ]; then
  echo "No command passed"
  exit 1
fi

cakePath=$(getCakeBasePath)
bootstrapFile="$cakePath/$bootstrapFileName"

# Check for the bootstrap script file
if [ ! -e "$bootstrapFile" ]; then
  echo "The file $bootstrapFile does not exist or isn't executable"
  exit 1;
fi

cd $cakePath
./$bootstrapFileName --target=$1
